### PR TITLE
Clean

### PR DESCRIPTION
**Pull request by AKuHAK**

### CODE REVIEW

**Comment by israpps** [comment]
Seems ok to me...

Removing those assets and moving back to remote theme removed some changes I made to the sidebar...

But I guess there is no harm...

Maybe adding a section for letting know the user where/how to submit reports?

**Review by israpps — APPROVED** [review]
seems ok

**Comment by AKuHAK** [comment]
> Maybe adding a section for letting know the user where/how to submit reports?

yeah it would be nice if you can found a way without injecting tons of files.

**Comment by AKuHAK** [comment]
Or we can just use the same template on OPL main repo and just copy them here

**Pull request merged**
